services:

  # Banco de dados para API Core
  pg-devtrails:
    image: bitnami/postgresql:latest
    container_name: pg-devtrails
    ports:
      - "5432:5432" # Porta do banco de dados
    environment:
      - POSTGRES_USER=devtrails
      - POSTGRES_PASSWORD=devtrails
      - POSTGRES_DB=devtrails_db