#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Gera o changeset antes de abrir o editor de commit
echo '📝 Generating changeset...'

npx changeset add || {
  echo '❌ Failed to generate changeset. Aborting commit.';
  exit 1;
}

# Adiciona os arquivos gerados ao stage para serem incluídos no commit
git add .changeset/*

echo '✅ Changeset generated and staged.'
